### ISSUE TITLE
查询报错502

### ISSUE THREAD

**Issue by Fhm-newbie** [zangxx66/jiwiki#5]
请问是我网络的问题吗？还是他网站的问题啊？上午还能正常用。。。
[2023-01-17 12:33:44,681 hoshino] ERROR: [Errno Expecting value] <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>

: 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/HoshinoBot/hoshino/modules/jiwiki/jiwiki.py", line 36, in query
    res = await resp.json()
  File "/root/HoshinoBot/hoshino/aiorequests.py", line 57, in json
    return await run_sync_func(self.raw_response.json, **kwargs)
  File "/root/HoshinoBot/hoshino/aiorequests.py", line 10, in run_sync_func
    return await asyncio.get_event_loop().run_in_executor(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>

: 0

**Comment by Fhm-newbie** [comment]
![Uploading Screenshot_20230117_124746_com.tencent.mobileqq_edit_346124655968539.jpg…]()

**Comment by Fhm-newbie** [comment]
![Screenshot_20230117_124746_com tencent mobileqq_edit_346124655968539](https://user-images.githubusercontent.com/63446200/212812409-ce8f6b15-2f37-48c0-a80d-49e41aabddd9.jpg)

**Comment by howrain** [comment]
看小鸡词典官网 已经被迫停止服务了（悲），据说因为和微博的官司

**Comment by Fhm-newbie** [comment]
寄
